//! Archetype table and King Wen sequence mapping for 64 Hexagrams.

/// Maps 6-bit binary index (0..63) to traditional King Wen order (1..64).
pub const KING_WEN_MAP: [u8; 64] = [
    2, 23, 8, 20, 16, 35, 45, 12, 15, 52, 39, 53, 62, 56, 31, 33,
    7, 4, 29, 59, 40, 64, 47, 6, 46, 18, 48, 57, 32, 50, 28, 44,
    24, 27, 3, 42, 51, 21, 17, 25, 36, 22, 63, 37, 55, 30, 49, 13,
    19, 41, 60, 61, 54, 38, 58, 10, 11, 26, 5, 9, 34, 14, 43, 1,
];

/// Returns the archetypal name for a King Wen hexagram number (1..64).
pub fn archetype_name(number: u8) -> &'static str {
    match number {
        1 => "The Creative (Heaven)",
        2 => "The Receptive (Earth)",
        3 => "Difficulty at the Beginning",
        4 => "Youthful Folly",
        5 => "Waiting (Nourishment)",
        6 => "Conflict",
        7 => "The Army",
        8 => "Holding Together (Union)",
        9 => "Small Taming",
        10 => "Treading (Conduct)",
        11 => "Peace",
        12 => "Standstill (Stagnation)",
        13 => "Fellowship with Men",
        14 => "Possession in Great Measure",
        15 => "Modesty",
        16 => "Enthusiasm",
        17 => "Following",
        18 => "Work on the Decayed",
        19 => "Approach",
        20 => "Contemplation (View)",
        21 => "Biting Through",
        22 => "Grace",
        23 => "Splitting Apart",
        24 => "Return (The Turning Point)",
        25 => "Innocence (The Unexpected)",
        26 => "Great Taming",
        27 => "Providing Nourishment",
        28 => "Preponderance of the Great",
        29 => "The Abyssal (Water)",
        30 => "The Clinging (Fire)",
        31 => "Influence (Wooing)",
        32 => "Duration",
        33 => "Retreat",
        34 => "Great Power",
        35 => "Progress",
        36 => "Darkening of the Light",
        37 => "The Family",
        38 => "Opposition",
        39 => "Obstruction",
        40 => "Deliverance",
        41 => "Decrease",
        42 => "Increase",
        43 => "Breakthrough (Resoluteness)",
        44 => "Coming to Meet",
        45 => "Gathering Together",
        46 => "Pushing Upward",
        47 => "Oppression (Exhaustion)",
        48 => "The Well",
        49 => "Revolution (Molting)",
        50 => "The Cauldron",
        51 => "The Arousing (Shock)",
        52 => "Keeping Still (Mountain)",
        53 => "Development (Gradual Progress)",
        54 => "The Marrying Maiden",
        55 => "Abundance",
        56 => "The Wanderer",
        57 => "The Gentle (Wind)",
        58 => "The Joyous (Lake)",
        59 => "Dispersion (Dissolution)",
        60 => "Limitation",
        61 => "Inner Truth",
        62 => "Small Preponderance",
        63 => "After Completion",
        64 => "Before Completion",
        _ => "The Harmonic Hexagram",
    }
}
